apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: busybox        
    image: busybox
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
  restartPolicy: Never

